# Country Touristic Indexes Cleanup

Jupyter Notebook for the cleanup of country touristic index database.

____________________________________________________________

For this process, the following CSV files are needed: 
* ```all_indexes_by_country.csv```

The CSV file has been generated by Marco Lupis, bechelor's degree student in Computer Science at the University of Modena and Reggio Emilia.

____________________________________________________________

In particular, the following operations are going to be executed:
* Opening of the CSV dataset
* Cleanup of the dataset

Lastly, the entire processed dump is going to be saved on disk in CSV format

In [1]:
# Libraries Import
import pandas as pd
import numpy as np 

pd.set_option('display.max_columns', None)

## File Paths
Please set your working directory paths.

In [2]:
# ******************* PATHS ********************+

# Dumps Directory Path
path_file_import = r'/Users/marcoterzulli/File/Scuola Local/Magistrale/Materiale Corsi Attuali/Tirocinio/Cartella di Lavoro/Archivi Dump di Lavoro/Import/'

# CSV Exports Directory Path
path_file_export = r'/Users/marcoterzulli/File/Scuola Local/Magistrale/Materiale Corsi Attuali/Tirocinio/Cartella di Lavoro/Archivi Dump di Lavoro/Export/'

## Dataset Import

In [3]:
df_country_touristic_indexes = pd.read_csv(path_file_import + 'all_indexes_by_country.csv', low_memory=False, index_col=[0])
df_country_touristic_indexes

,Country,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,TTCI,EE,TTPEC,INF,NCR,BE,SS,HH,HRLM,ICTR,PTT,IO,PC,ES,ATI,GPI,TSI,NR,CRBT
ConferenceLocation,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
"Austin, Texas, United States",United States,79732.0,82756.0,82525.0,74767.0,75796.0,78343.0,70975.0,64434.0,62082.0,67606.0,71484.0,183178.0,175299.0,175703.0,160508.0,162275.0,147271.416,171629.897,179309.907,178311.354,176864.526,175261.488,174291.746,169324.918,165478.0,45037.0,5.3,5.8,4.6,5.8,4.9,5.8,5.6,5.8,5.8,6.0,5.5,4.0,4.7,4.1,5.9,4.9,6.6,5.0,4.7
"Wroc≈Çaw, Lower Silesian Voivodeship, Poland",Poland,82244.0,87439.0,87817.0,88592.0,89118.0,84515.0,61431.0,50735.0,52130.0,61918.0,64606.0,65115.0,66208.0,59935.0,53840.0,58340.0,60745.000,67390.000,72310.000,73750.000,77743.000,80476.000,83804.000,85946.000,88515.0,51076.0,4.2,5.3,4.5,4.0,3.1,4.3,5.6,6.3,4.8,5.5,4.2,4.1,5.7,4.2,3.2,4.3,4.5,3.2,3.0
"Innsbruck, Tyrol, Austria",Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.9,4.9,5.4,3.6,4.8,6.2,7.0,5.3,6.1,5.3,4.0,4.7,5.7,4.2,5.2,6.7,4.1,3.2
"Villefranche-sur-Sa√¥ne, Auvergne-Rh√¥ne-Alpes, France",France,NaN,148263.0,157551.0,NaN,NaN,NaN,NaN,NaN,NaN,190282.0,185829.0,193882.0,193319.0,193571.0,192369.0,189826.0,196595.000,197522.000,204410.000,206599.000,203302.000,203042.000,207274.000,211998.000,217877.0,117109.0,5.4,5.6,4.8,5.4,5.9,4.8,5.7,6.5,5.1,5.9,5.1,4.2,4.5,5.3,4.8,5.6,5.7,4.9,6.8
"Zakopane, Lesser Poland Voivodeship, Poland",Poland,82244.0,87439.0,87817.0,88592.0,89118.0,84515.0,61431.0,50735.0,52130.0,61918.0,64606.0,65115.0,66208.0,59935.0,53840.0,58340.0,60745.000,67390.000,72310.000,73750.000,77743.000,80476.000,83804.000,85946.000,88515.0,51076.0,4.2,5.3,4.5,4.0,3.1,4.3,5.6,6.3,4.8,5.5,4.2,4.1,5.7,4.2,3.2,4.3,4.5,3.2,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Veneto, Italy",Italy,55706.0,59805.0,57998.0,58499.0,59521.0,62702.0,60960.0,63561.0,63026.0,58480.0,59230.0,66353.0,70271.0,70719.0,71692.0,73225.0,75866.000,76293.000,76762.000,77694.000,81068.000,84925.000,89931.000,93228.600,95399.0,38419.0,5.1,5.2,4.4,5.0,5.7,4.0,5.5,6.3,4.6,5.5,4.8,4.1,4.4,4.3,4.4,4.7,6.0,4.9,6.5
"Bastia, Corsica, France",France,NaN,148263.0,157551.0,NaN,NaN,NaN,NaN,NaN,NaN,190282.0,185829.0,193882.0,193319.0,193571.0,192369.0,189826.0,196595.000,197522.000,204410.000,206599.000,203302.000,203042.000,207274.000,211998.000,217877.0,117109.0,5.4,5.6,4.8,5.4,5.9,4.8,5.7,6.5,5.1,5.9,5.1,4.2,4.5,5.3,4.8,5.6,5.7,4.9,6.8
"Laramie, Wyoming, United States",United States,79732.0,82756.0,82525.0,74767.0,75796.0,78343.0,70975.0,64434.0,62082.0,67606.0,71484.0,183178.0,175299.0,175703.0,160508.0,162275.0,147271.416,171629.897,179309.907,178311.354,176864.526,175261.488,174291.746,169324.918,165478.0,45037.0,5.3,5.8,4.6,5.8,4.9,5.8,5.6,5.8,5.8,6.0,5.5,4.0,4.7,4.1,5.9,4.9,6.6,5.0,4.7
"Longyearbyen, Norway",Norway,NaN,NaN,NaN,5045.0,5123.0,5121.0,5115.0,4543.0,4686.0,5130.0,5418.0,5738.0,6017.0,6054.0,6114.0,6578.0,6693.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6,5.9,4.9,4.9,2.7,5.3,6.1,6.4,5.5,6.3,5.4,4.0,4.2,5.8,5.6,3.9,5.1,3.2,2.2
"Shijiazhuang City, Hebei, China",China,46387.0,51128.0,57588.0,63478.0,72796.0,83444.0,89013.0,97908.0,91662.0,109038.0,120292.0,124942.0,131873.0,130027.0,126476.0,133762.0,135423.000,132405.000,129078.000,128499.000,133820.000,141774.000,153260.000,158606.000,162538.0,30402.0,4.9,5.2,4.3,3.9,6.1,4.7,5.6,5.6,5.2,5.0,4.8,3.1,5.7,3.8,4.3,3.9,3.5,5.1,7.0

## Dataset Cleanup

#### Reindexing

In [4]:
df_country_touristic_indexes = df_country_touristic_indexes.reset_index(level=0)
df_country_touristic_indexes = df_country_touristic_indexes.rename(columns={"index": "ConferenceLocation"})
df_country_touristic_indexes.drop(columns=["ConferenceLocation"], inplace = True)

df_country_touristic_indexes

,Country,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,TTCI,EE,TTPEC,INF,NCR,BE,SS,HH,HRLM,ICTR,PTT,IO,PC,ES,ATI,GPI,TSI,NR,CRBT
0,United States,79732.0,82756.0,82525.0,74767.0,75796.0,78343.0,70975.0,64434.0,62082.0,67606.0,71484.0,183178.0,175299.0,175703.0,160508.0,162275.0,147271.416,171629.897,179309.907,178311.354,176864.526,175261.488,174291.746,169324.918,165478.0,45037.0,5.3,5.8,4.6,5.8,4.9,5.8,5.6,5.8,5.8,6.0,5.5,4.0,4.7,4.1,5.9,4.9,6.6,5.0,4.7
1,Poland,82244.0,87439.0,87817.0,88592.0,89118.0,84515.0,61431.0,50735.0,52130.0,61918.0,64606.0,65115.0,66208.0,59935.0,53840.0,58340.0,60745.000,67390.000,72310.000,73750.000,77743.000,80476.000,83804.000,85946.000,88515.0,51076.0,4.2,5.3,4.5,4.0,3.1,4.3,5.6,6.3,4.8,5.5,4.2,4.1,5.7,4.2,3.2,4.3,4.5,3.2,3.0
2,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.9,4.9,5.4,3.6,4.8,6.2,7.0,5.3,6.1,5.3,4.0,4.7,5.7,4.2,5.2,6.7,4.1,3.2
3,France,NaN,148263.0,157551.0,NaN,NaN,NaN,NaN,NaN,NaN,190282.0,185829.0,193882.0,193319.0,193571.0,192369.0,189826.0,196595.000,197522.000,204410.000,206599.000,203302.000,203042.000,207274.000,211998.000,217877.0,117109.0,5.4,5.6,4.8,5.4,5.9,4.8,5.7,6.5,5.1,5.9,5.1,4.2,4.5,5.3,4.8,5.6,5.7,4.9,6.8
4,Poland,82244.0,87439.0,87817.0,88592.0,89118.0,84515.0,61431.0,50735.0,52130.0,61918.0,64606.0,65115.0,66208.0,59935.0,53840.0,58340.0,60745.000,67390.000,72310.000,73750.000,77743.000,80476.000,83804.000,85946.000,88515.0,51076.0,4.2,5.3,4.5,4.0,3.1,4.3,5.6,6.3,4.8,5.5,4.2,4.1,5.7,4.2,3.2,4.3,4.5,3.2,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2465,Italy,55706.0,59805.0,57998.0,58499.0,59521.0,62702.0,60960.0,63561.0,63026.0,58480.0,59230.0,66353.0,70271.0,70719.0,71692.0,73225.0,75866.000,76293.000,76762.000,77694.000,81068.000,84925.000,89931.000,93228.600,95399.0,38419.0,5.1,5.2,4.4,5.0,5.7,4.0,5.5,6.3,4.6,5.5,4.8,4.1,4.4,4.3,4.4,4.7,6.0,4.9,6.5
2466,France,NaN,148263.0,157551.0,NaN,NaN,NaN,NaN,NaN,NaN,190282.0,185829.0,193882.0,193319.0,193571.0,192369.0,189826.0,196595.000,197522.000,204410.000,206599.000,203302.000,203042.000,207274.000,211998.000,217877.0,117109.0,5.4,5.6,4.8,5.4,5.9,4.8,5.7,6.5,5.1,5.9,5.1,4.2,4.5,5.3,4.8,5.6,5.7,4.9,6.8
2467,United States,79732.0,82756.0,82525.0,74767.0,75796.0,78343.0,70975.0,64434.0,62082.0,67606.0,71484.0,183178.0,175299.0,175703.0,160508.0,162275.0,147271.416,171629.897,179309.907,178311.354,176864.526,175261.488,174291.746,169324.918,165478.0,45037.0,5.3,5.8,4.6,5.8,4.9,5.8,5.6,5.8,5.8,6.0,5.5,4.0,4.7,4.1,5.9,4.9,6.6,5.0,4.7
2468,Norway,NaN,NaN,NaN,5045.0,5123.0,5121.0,5115.0,4543.0,4686.0,5130.0,5418.0,5738.0,6017.0,6054.0,6114.0,6578.0,6693.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6,5.9,4.9,4.9,2.7,5.3,6.1,6.4,5.5,6.3,5.4,4.0,4.2,5.8,5.6,3.9,5.1,3.2,2.2
2469,China,46387.0,51128.0,57588.0,63478.0,72796.0,83444.0,89013.0,97908.0,91662.0,109038.0,120292.0,124942.0,131873.0,130027.0,126476.0,133762.0,135423.000,132405.000,129078.000,128499.000,133820.000,141774.000,153260.000,158606.000,162538.0,30402.0,4.9,5.2,4.3,3.9,6.1,4.7,5.6,5.6,5.2,5.0,4.8,3.1,5.7,3.8,4.3,3.9,3.5,5.1,7.0

#### Drop of the Duplicated Values

In [5]:
df_country_touristic_indexes = df_country_touristic_indexes.drop_duplicates(subset=["Country"])
df_country_touristic_indexes

,Country,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,TTCI,EE,TTPEC,INF,NCR,BE,SS,HH,HRLM,ICTR,PTT,IO,PC,ES,ATI,GPI,TSI,NR,CRBT
0,United States,79732.0,82756.0,82525.0,74767.0,75796.0,78343.0,70975.0,64434.0,62082.0,67606.0,71484.0,183178.0,175299.0,175703.0,160508.0,162275.0,147271.416,171629.897,179309.907,178311.354,176864.526,175261.488,174291.746,169324.918,165478.0,45037.0,5.3,5.8,4.6,5.8,4.9,5.8,5.6,5.8,5.8,6.0,5.5,4.0,4.7,4.1,5.9,4.9,6.6,5.0,4.7
1,Poland,82244.0,87439.0,87817.0,88592.0,89118.0,84515.0,61431.0,50735.0,52130.0,61918.0,64606.0,65115.0,66208.0,59935.0,53840.0,58340.0,60745.000,67390.000,72310.000,73750.000,77743.000,80476.000,83804.000,85946.000,88515.0,51076.0,4.2,5.3,4.5,4.0,3.1,4.3,5.6,6.3,4.8,5.5,4.2,4.1,5.7,4.2,3.2,4.3,4.5,3.2,3.0
2,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.9,4.9,5.4,3.6,4.8,6.2,7.0,5.3,6.1,5.3,4.0,4.7,5.7,4.2,5.2,6.7,4.1,3.2
3,France,NaN,148263.0,157551.0,NaN,NaN,NaN,NaN,NaN,NaN,190282.0,185829.0,193882.0,193319.0,193571.0,192369.0,189826.0,196595.000,197522.000,204410.000,206599.000,203302.000,203042.000,207274.000,211998.000,217877.0,117109.0,5.4,5.6,4.8,5.4,5.9,4.8,5.7,6.5,5.1,5.9,5.1,4.2,4.5,5.3,4.8,5.6,5.7,4.9,6.8
5,Portugal,23066.0,23252.0,24244.0,26560.0,27016.0,28014.0,28150.0,27194.0,27532.0,21165.0,21173.0,22588.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.9,5.5,4.8,5.2,4.0,4.7,6.3,6.0,5.1,5.5,5.7,4.2,5.1,4.2,4.7,4.2,6.7,4.0,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2254,El Salvador,NaN,NaN,NaN,NaN,NaN,867.0,804.0,885.0,798.0,1030.0,1306.0,1501.0,1720.0,1875.0,1482.0,1606.0,1634.000,1738.000,1822.000,1886.000,1973.000,2052.000,2247.000,2536.000,2639.0,707.0,3.2,3.9,4.6,2.7,1.7,3.6,3.0,5.1,3.7,4.2,4.3,4.6,5.7,3.8,2.1,2.9,3.1,2.2,1.3
2298,Bahrain,2311.0,1988.0,2600.0,2898.0,3280.0,3869.0,4388.0,4831.0,4844.0,5667.0,6313.0,7289.0,7833.0,8631.0,8861.0,11952.0,6732.000,8062.000,9163.000,10452.000,9670.000,10158.000,11374.000,12045.000,11061.0,1909.0,3.9,5.5,4.3,4.4,1.4,5.4,5.9,5.2,4.9,5.8,4.5,2.9,5.8,4.1,3.5,5.2,4.6,1.6,1.2
2367,Saint Kitts and Nevis,203.0,172.0,194.0,250.0,226.0,247.0,334.0,240.0,247.0,383.0,365.0,350.0,379.0,533.0,548.0,624.0,723.000,666.000,695.000,818.000,1036.000,1055.000,1194.000,1278.000,1107.0,301.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2461,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2463,Botswana,636.0,656.0,765.0,940.0,1039.0,1306.0,1451.0,1485.0,1592.0,1727.0,1684.0,1642.0,1965.0,2344.0,NaN,NaN,NaN,NaN,NaN,NaN,1660.000,1712.000,1775.000,1830.000,NaN,NaN,3.5,4.4,4.4,2.8,2.3,4.9,5.3,3.3,4.3,4.1,4.8,2.3,6.0,4.3,2.1,2.8,3.6,3.4,1.2

#### Fix of the Data Types

In [6]:
cols= [i for i in df_country_touristic_indexes.columns if i not in ["Country"]]
for col in cols:
    df_country_touristic_indexes[col] = pd.to_numeric(df_country_touristic_indexes[col])

/var/folders/gy/9drryydn41lddmpgtpzzxrgw0000gn/T/ipykernel_11002/3549868062.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_country_touristic_indexes[col] = pd.to_numeric(df_country_touristic_indexes[col])

## Dataset Split

We're going to split the dataframe in two parts:
* Yearly Tourist Arrivals
* Touristic Indexes

This will allow us to use the dataset in a simpler way.

#### Drop of the Touristic Indexes Columns

Before doing this, remember to specify the year range in the following cell:

In [7]:
start_year = 1995
final_year = 2020

In [8]:
df_country_yearly_tourist_arrivals = df_country_touristic_indexes.copy()

column_to_drop = list(set(df_country_yearly_tourist_arrivals.columns.values.tolist()) - set([str(x) for x in range(start_year, final_year + 1)]) - set(["Country"]))

df_country_yearly_tourist_arrivals = df_country_yearly_tourist_arrivals.drop(column_to_drop, axis=1)
df_country_yearly_tourist_arrivals.head(3)

,Country,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,United States,79732.0,82756.0,82525.0,74767.0,75796.0,78343.0,70975.0,64434.0,62082.0,67606.0,71484.0,183178.0,175299.0,175703.0,160508.0,162275.0,147271.416,171629.897,179309.907,178311.354,176864.526,175261.488,174291.746,169324.918,165478.0,45037.0
1,Poland,82244.0,87439.0,87817.0,88592.0,89118.0,84515.0,61431.0,50735.0,52130.0,61918.0,64606.0,65115.0,66208.0,59935.0,53840.0,58340.0,60745.000,67390.000,72310.000,73750.000,77743.000,80476.000,83804.000,85946.000,88515.0,51076.0
2,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Drop of the Tourist Arrival Columns

In [9]:
column_to_drop = [str(x) for x in range(start_year, final_year + 1)]

df_country_touristic_indexes = df_country_touristic_indexes.drop(column_to_drop, axis=1)
df_country_touristic_indexes.head(3)

,Country,TTCI,EE,TTPEC,INF,NCR,BE,SS,HH,HRLM,ICTR,PTT,IO,PC,ES,ATI,GPI,TSI,NR,CRBT
0,United States,5.3,5.8,4.6,5.8,4.9,5.8,5.6,5.8,5.8,6.0,5.5,4.0,4.7,4.1,5.9,4.9,6.6,5.0,4.7
1,Poland,4.2,5.3,4.5,4.0,3.1,4.3,5.6,6.3,4.8,5.5,4.2,4.1,5.7,4.2,3.2,4.3,4.5,3.2,3.0
2,Austria,5.0,5.9,4.9,5.4,3.6,4.8,6.2,7.0,5.3,6.1,5.3,4.0,4.7,5.7,4.2,5.2,6.7,4.1,3.2

## Write of the Final CSV on Disk

Saving the resulting dataframe on disk in CSV format.

In [10]:
# Write of the resulting CSVs on Disk
df_country_touristic_indexes.to_csv(path_file_export + 'out_country_touristc_indexes.csv')
print(f'Successfully Exported the Processed CSV to {path_file_export}out_country_touristc_indexes.csv')


df_country_yearly_tourist_arrivals.to_csv(path_file_export + 'out_country_yearly_tourist_arrivals.csv')
print(f'Successfully Exported the Processed CSV to {path_file_export}out_country_yearly_tourist_arrivals.csv')

Successfully Exported the Processed CSV to /Users/marcoterzulli/File/Scuola Local/Magistrale/Materiale Corsi Attuali/Tirocinio/Cartella di Lavoro/Archivi Dump di Lavoro/Export/out_country_touristc_indexes.csv
Successfully Exported the Processed CSV to /Users/marcoterzulli/File/Scuola Local/Magistrale/Materiale Corsi Attuali/Tirocinio/Cartella di Lavoro/Archivi Dump di Lavoro/Export/out_country_yearly_tourist_arrivals.csv

Check of the Exported CSVs to be sure that everything went fine.

In [11]:
# Check of the Exported CSV
df_country_touristic_indexes_exported_csv = pd.read_csv(path_file_export + 'out_country_touristc_indexes.csv', low_memory=False, index_col=[0])
df_country_touristic_indexes_exported_csv

,Country,TTCI,EE,TTPEC,INF,NCR,BE,SS,HH,HRLM,ICTR,PTT,IO,PC,ES,ATI,GPI,TSI,NR,CRBT
0,United States,5.3,5.8,4.6,5.8,4.9,5.8,5.6,5.8,5.8,6.0,5.5,4.0,4.7,4.1,5.9,4.9,6.6,5.0,4.7
1,Poland,4.2,5.3,4.5,4.0,3.1,4.3,5.6,6.3,4.8,5.5,4.2,4.1,5.7,4.2,3.2,4.3,4.5,3.2,3.0
2,Austria,5.0,5.9,4.9,5.4,3.6,4.8,6.2,7.0,5.3,6.1,5.3,4.0,4.7,5.7,4.2,5.2,6.7,4.1,3.2
3,France,5.4,5.6,4.8,5.4,5.9,4.8,5.7,6.5,5.1,5.9,5.1,4.2,4.5,5.3,4.8,5.6,5.7,4.9,6.8
5,Portugal,4.9,5.5,4.8,5.2,4.0,4.7,6.3,6.0,5.1,5.5,5.7,4.2,5.1,4.2,4.7,4.2,6.7,4.0,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2254,El Salvador,3.2,3.9,4.6,2.7,1.7,3.6,3.0,5.1,3.7,4.2,4.3,4.6,5.7,3.8,2.1,2.9,3.1,2.2,1.3
2298,Bahrain,3.9,5.5,4.3,4.4,1.4,5.4,5.9,5.2,4.9,5.8,4.5,2.9,5.8,4.1,3.5,5.2,4.6,1.6,1.2
2367,Saint Kitts and Nevis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2461,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2463,Botswana,3.5,4.4,4.4,2.8,2.3,4.9,5.3,3.3,4.3,4.1,4.8,2.3,6.0,4.3,2.1,2.8,3.6,3.4,1.2

In [12]:
# Check of the Exported CSV
out_country_yearly_tourist_arrivals = pd.read_csv(path_file_export + 'out_country_yearly_tourist_arrivals.csv', low_memory=False, index_col=[0])
out_country_yearly_tourist_arrivals

,Country,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,United States,79732.0,82756.0,82525.0,74767.0,75796.0,78343.0,70975.0,64434.0,62082.0,67606.0,71484.0,183178.0,175299.0,175703.0,160508.0,162275.0,147271.416,171629.897,179309.907,178311.354,176864.526,175261.488,174291.746,169324.918,165478.0,45037.0
1,Poland,82244.0,87439.0,87817.0,88592.0,89118.0,84515.0,61431.0,50735.0,52130.0,61918.0,64606.0,65115.0,66208.0,59935.0,53840.0,58340.0,60745.000,67390.000,72310.000,73750.000,77743.000,80476.000,83804.000,85946.000,88515.0,51076.0
2,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,France,NaN,148263.0,157551.0,NaN,NaN,NaN,NaN,NaN,NaN,190282.0,185829.0,193882.0,193319.0,193571.0,192369.0,189826.0,196595.000,197522.000,204410.000,206599.000,203302.000,203042.000,207274.000,211998.000,217877.0,117109.0
5,Portugal,23066.0,23252.0,24244.0,26560.0,27016.0,28014.0,28150.0,27194.0,27532.0,21165.0,21173.0,22588.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2254,El Salvador,NaN,NaN,NaN,NaN,NaN,867.0,804.0,885.0,798.0,1030.0,1306.0,1501.0,1720.0,1875.0,1482.0,1606.0,1634.000,1738.000,1822.000,1886.000,1973.000,2052.000,2247.000,2536.000,2639.0,707.0
2298,Bahrain,2311.0,1988.0,2600.0,2898.0,3280.0,3869.0,4388.0,4831.0,4844.0,5667.0,6313.0,7289.0,7833.0,8631.0,8861.0,11952.0,6732.000,8062.000,9163.000,10452.000,9670.000,10158.000,11374.000,12045.000,11061.0,1909.0
2367,Saint Kitts and Nevis,203.0,172.0,194.0,250.0,226.0,247.0,334.0,240.0,247.0,383.0,365.0,350.0,379.0,533.0,548.0,624.0,723.000,666.000,695.000,818.000,1036.000,1055.000,1194.000,1278.000,1107.0,301.4
2461,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2463,Botswana,636.0,656.0,765.0,940.0,1039.0,1306.0,1451.0,1485.0,1592.0,1727.0,1684.0,1642.0,1965.0,2344.0,NaN,NaN,NaN,NaN,NaN,NaN,1660.000,1712.000,1775.000,1830.000,NaN,NaN